### ISSUE TITLE
Feature request - Autotune basal

### ISSUE THREAD

**Issue by zarinanoodle** [Artificial-Pancreas/iAPS#202]
Hi! 
I would love it if there was a way to quickly port the autotune results (especially the basal) from the autotune screen to the settings itself.

This is especially useful/cumbersome for women during the different cycles of the month because as hormones fluctuate so do basals, during pregnancy because basals change every week or sometimes even every other day and it is definitely very difficult/cumbersome to change over 24h worth of basals over every other day.
Obviously everyone benefits from this but if your hormones change frequently like women generally, those with hormone imbalances, or if you’re loosing weight/using Metformin or Glp-1/2 antagonists (like Wagovy and similar) your basals change like every other day and manually changing them over is a whole chore.

I would really, really appreciate if this could be looked into 🙏🏻, I spend a good 10-15 mins every other day changing basals 😭

**Comment by scrappy** [comment]
For this sort of thing, the new iAPS already has the ability to turn Autotune on for *just* basals ... so you do not have to port anything over, just turn it on ...

That said, one of my patients just had a situation where this feature would be useful ... her phone died overnight, which means she was operating on pump basal's instead of Autotune ones, and went a bit low by morning ...

But again, in your case above, just Turn Autotune + Basals Only one, which will have the same effect, but without you having to change your scheduled.

If autotune is on + basals only, your scheduled basals are ignored ... the autotune ones take effect.

**Comment by Jon-b-m** [comment]
This is now implemented in dev branch
