### ISSUE TITLE
New feature request. Temp basal duration configuration 

### ISSUE THREAD

**Issue by Chester-sk8** [Artificial-Pancreas/iAPS#237]
It would be great if user could change duration of temp basal = 0 (when smb is planned). 
Reason: today night iaps set temp basal = 0 for 90 minutes. 5 minutes later iaps connection to pump was failed and it was “red loop” for the whole night. 
Because of some cob I had bg increase untill basal wasn’t started and insulin started acting.

**Comment by Jon-b-m** [comment]
This is the whole point os SMB, to deliver insulin as small boluses instead of temp basals, thus when delivering insulin as an SMB the basal is shut off. If you don't like the dosing to only happen via SMBs you can decrease the SMB basal minutes or turn of SMBs, to increase the use of temporary basal insulin instead.
