### ISSUE TITLE
Feature request: BG visible on Watch

### ISSUE THREAD

**Issue by redomo** [Artificial-Pancreas/iAPS#434]
Would like to see current/actual BG on the iWatch. This should then be instead or over the iAPS icon on the watch. (similar to what Loop displays on their watch app icon)

**Comment by MikePlante1** [comment]
I disagree with adding a bg # to the iAPS watch complication, since complications are very often out-of-date by 15 minutes or more which could prove dangerous.

The only way to get a reliably updated cgm reading on the watch face is to use calendar entries, which is available by going to ⚙️>cgm>Create Events in Calendar. Unfortunately though, watchOS10 has been causing problems with this feature as well.

**Comment by darrelld3** [comment]
BG# would be a nice feature as long as the last update time was displayed along with BG#.

Medtronic is doing Apple Watch integration with their 780G.

Reference link is here;
getting_started_with_the_minimed_mobile_app_with_apple_watch_pdf.pdf (medtronic-diabetes.com)<https://resources.cloud.medtronic-diabetes.com/sites/prd/files/documents/2023-06/getting_started_with_the_minimed_mobile_app_with_apple_watch_pdf.pdf>

From: MikePlante1 ***@***.***>
Date: Monday, February 5, 2024 at 10:42 PM
To: Artificial-Pancreas/iAPS ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [Artificial-Pancreas/iAPS] Feature request: BG visible on Watch (Issue #434)

I disagree with adding a bg # to the iAPS watch complication, since complications are very often out-of-date by 15 minutes or more which could prove dangerous.

The only way to get a reliably updated cgm reading on the watch face is to use calendar entries, which is available by going to ⚙️>cgm>Create Events in Calendar. Unfortunately though, watchOS10 has been causing problems with this feature as well.

**Comment by mholstfernsten** [comment]
I totally agree with @redomo that this would be a very good feature. Used Loopkit before and I like that solution where the watch icon are showing BG. I never had an issue with the BG being out of sync.

**Comment by Jon-b-m** [comment]
This now possible using the Apple Contact complication

**Comment by magnusholstfernsten** [comment]
> This now possible using the Apple Contact complication 

Is it possible to make that linked to the app?

**Comment by Jon-b-m** [comment]
Yes. There is an iAPS settings submenu for this
