### ISSUE TITLE
Feature request: Add support for the Freestyle Libre 2 Plus

### ISSUE THREAD

**Issue by MalHusky** [Artificial-Pancreas/iAPS#501]
The Freestyle Libre 2 Plus sensor was recently released. It was designed to be compatible for use with AID systems. It is available for use with Tandem's t:slim X2. I don't know how similar the communication protocol is to the currently supported European Libre 2, but this would be a welcome addition to the list of supported sensors for those without access to the EU sensor. Sensor accuracy and wear time are reported to be as good or better than the Libre 2.

**Comment by straykatz** [comment]
I would totally use a loopable US-available FSL2! 

(I am visiting France right now and will bring FLS2s home ... I love so many things about them - they have a great form factor (I guess the DexG7 is similar), but most of all, I love the scanning feature - when I swim, I can just scan for bg and don't have to wait for it it reconnect. Big change! 

Plus 1 :-)

**Comment by gui-dos** [comment]
The Libre 2 Plus is a “Gen2” device like the US, CA and AU model, so the enhanced secured connections require to follow multi-stage challenge-response protocols that I am outlining in https://github.com/gui-dos/DiaBLE/blob/main/DiaBLE/Gen2.swift.

The European Libre Sense "biosensor" by Supersapiens already belongs to the same family: you can notice in fact that they are going to target the diabetic patients soon, too: https://diabetes.supersapiens.com/ .

**Comment by MalHusky** [comment]
This sounds very promising. I was hoping this new sensor would have a similar communication protocol to the existing European Libre 2, especially since the 2 Plus was designed for use in an AID environment. I would expect the Libre 3 Plus to follow.

I wasn't familiar with Supersapiens . Looks like that could generate some very useful information. Info I wish I had years ago.

**Comment by MalHusky** [comment]
> I would totally use a loopable US-available FSL2! 

I'm hoping the Libre 3 Plus comes out this year. Smaller form factor than the Libre 2. I started with a Dexcom G4. That was a pain in more ways than one, but it worked. However, insurance decided to no longer cover any CGM so I went with the Libre since I had to pay for it myself and it was less expensive than Dexcom. I haven't found a good reason to go back, especially if iAPS will support the Libre 2+. I'm looking forward to trying iAPS.

**Comment by straykatz** [comment]
If you pay for it yourself, then there is one very good reason to go back to Dexcom G6: Anubis transmitters. For me at least - the hacked Anubis transmitter allows me to use each CGM sensor for as long as it provides good readings/falls off. I think 30 days is the longest I was able to use one. Sent from the pocket communicator.On Feb 19, 2024, at 02:47, MalHusky ***@***.***> wrote:﻿

I would totally use a loopable US-available FSL2!

I'm hoping the Libre 3 Plus comes out this year. Smaller form factor than the Libre 2. I started with a Dexcom G4. That was a pain in more ways than one, but it worked. However, insurance decided to no longer cover any CGM so I went with the Libre since I had to pay for it myself and it was less expensive than Dexcom. I haven't found a good reason to go back, especially if iAPS will support the Libre 2+. I'm looking forward to trying iAPS.

**Comment by MalHusky** [comment]
Now that's very interesting and definitely makes the Dexcom more cost effective. I wasn't aware that Anubis existed but I think there were workarounds for extending the life of Dexcom transmitters. Not sure if any actually worked. However, after about a year and a half I finally convinced the insurance company to cover CGMs.  And now a lot of insurance plans cover them, at varying copays of course.  I've grown to like the slightly smaller size, extended wear time and fewer parts of the Libre. I suppose a G7 might be an option. My concern now is how well Libre 2+ will work in an AID system like iAPS. If the European Libre 2 is working then I would hope for the same here.

**Comment by MalHusky** [comment]
Sorry, didn't mean to close this out.

**Comment by Jon-b-m** [comment]
Done for the European libre plus

**Comment by MalHusky** [comment]
Would be nice to have a US version working with iAPS. I suspect the 3+ may become Abbott's prime CGM sensor.
