### ISSUE TITLE
APS error: Determine basal failed

### ISSUE THREAD

**Issue by bamtoriscout** [Artificial-Pancreas/iAPS#774]
I'm new user
but I met 'APS error: Determine basal failed'
what is my problem?
![IMG_1321](https://github.com/user-attachments/assets/ff3ea50a-4810-4dc0-acf9-c717eb6385a6)
![IMG_1322](https://github.com/user-attachments/assets/d300f659-adb6-46b8-8aae-fd2e237b9875)
![IMG_1323](https://github.com/user-attachments/assets/e4e453b7-3322-4a77-b462-c3adf7bd8b97)
![IMG_1324](https://github.com/user-attachments/assets/c2b80c2a-ff0f-485e-87b5-7da3ab2b2fd2)
![IMG_1325](https://github.com/user-attachments/assets/df580b81-ffec-4dfc-a756-3d034caa024e)
![IMG_1326](https://github.com/user-attachments/assets/c2586a08-41ad-4c7c-9b82-6f7866f5571b)

**Comment by Jon-b-m** [comment]
Please update to latest iAPS v4.6.0. There are core algorithm issues in older iAPS forks (v2 and TRIO).

**Comment by MikePlante1** [comment]
> Please update to latest iAPS v4.6.0. There are core algorithm issues in older iAPS forks (v2 and TRIO).

So without requesting a log, you determined this to absolutely definitely be caused by a "core algorithm issue"?

Because "APS Error: Determine basal failed" is a normal error that can be caused by many things that can absolutely still occur in v4.6.0

If you don't want to bother looking at the log for an older version of the app (completely understandable), a better response would have been something like "This looks like an older version that's no longer supported. Please update to the latest version and report again if this error still occurs".

And once again, please don't make comments on *Trio, especially when it wasn't even mentioned in this issue report, since you've already admitted to not following that project at all and therefore don't actually know anything about it. You apparently can't even get the formatting of the name right, much less any important details.

**Comment by darrelld3** [comment]
Completly unhinged and unnecessary comment.
________________________________

**Comment by dnzxy** [comment]
@bamtoriscout would you care to please post a screenshot of your settings menu in the app when scrolled all the way to the top, where it shows your build branch, expiry date and information about which app/version you are running.

Alternatively, please provide log files (can be found under your phone's Files > On my iphone > folder `name of app`> folder `logs`.

Thank you 😄

**Comment by Sharpyuk** [comment]
I have this same issue on 6.4.6 (1) - Main 6704cf2

App is new, using latest build.. and built last night

I'm using Omnipod Dash, and xDrip4iOS for CGM (Libre 2 EU sensor)

Any idea what may be causing this?
